DatabaseProjectSample/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('connective.urls')),
]

connective/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.success, name='home'),
    path('reg/', views.Contactform, name='reg'),
    path('login', views.logindata, name='log'),
    path('logout', views.logout, name='logout'),
    path('show', views.show, name='show'),
    path('delete/<int:id>', views.destroy),
]

connective/models.py
from django.db import models

# Create your models here.

class ContactForm(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    contact = models.CharField(max_length=100)
    password = models.TextField(max_length=100)

connective/forms.py
from django import forms
from .models import ContactForm

class FormAddContactForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = ContactForm
        fields = ['name', 'email', 'contact', 'password']

connective/views.py
from django.shortcuts import render, redirect
from .forms import FormAddContactForm
from .models import ContactForm
from django.contrib import messages

# Create your views here.

def Contactform(request):
    form = FormAddContactForm()
    data = {
        'form': form
    }
    if request.method == 'POST':
        form = FormAddContactForm(request.POST)
        if form.is_valid():
            name = request.POST['name']
            email = request.POST['email']
            contact = request.POST['contact']
            password = request.POST['password']
            re_password = request.POST['re_password']

            if ContactForm.objects.filter(name=name).exists():
                messages.error(request, "Name must be different")

            elif ContactForm.objects.filter(email=email).exists():
                messages.error(request, "Email must be different")

            elif ContactForm.objects.filter(contact=contact).exists():
                messages.error(request, "Contact must be different")

            elif password != re_password:
                messages.error(request, "Password must be same")

            else:
                form.save()
                return render(request, 'success.html')

    return render(request, 'contact.html', {'form':data})

def success(request):
    employees = ContactForm.objects.all()
    return render(request, 'success.html', {'employees':employees})

def logindata(request):
    if request.method == 'POST':
        try:
            userdetail = ContactForm.objects.get(email = request.POST['email'], password = request.POST['password'])
            request.session['email']=userdetail.email
            return render(request, 'success.html')
        except ContactForm.DoesNotExist as e:
            messages.success(request, 'Email / Password is Invalid..!')
    return render(request, 'login.html')

def logout(request):
    try:
        del request.session['email']
    except:
        return render(request, 'success.html')
    return render(request, 'success.html')

def show(request):
    employees = ContactForm.objects.all()
    return render(request, 'show.html', {'employees':employees})

def destroy(request, id):
    employee = ContactForm.objects.get(id=id)
    employee.delete()
    return redirect('/show')

connective/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}

    <link href="{% static '/css/base.css' %}" rel="stylesheet" type="text/css">
    <!-- favicon start -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'img/favicon/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'img/favicon/safari-pinned-tab.svg' %}" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <!-- favicon end -->

    {% block head %}
        {% block title %} {% endblock title %}
    {% endblock head %}
</head>
<body>
    <header>
        <div class="header-block">
            <div class="logo">
                <h2>Logbook</h2>
            </div>
            <div class="link">
                <div>
                    Login Connectivity :
                    <a href="{% url 'home' %}">Home</a> &nbsp; &nbsp;
                    <a href="{% url 'reg' %}">Registration</a> &nbsp; &nbsp;
                    <a href="{% url 'log' %}">Login</a>
                    <a href="{% url 'show' %}">Show</a>
                    {% block connectivity %}
                    {% endblock connectivity %}
                </div>
            </div>
        </div>
        {% block header %}
        {% endblock header %}
    </header>
    {% block content %} {% endblock content %}
</body>
</html>

connective/templates/contact.html
{% extends 'base.html' %}

{% block head %}
    {% load static %}
    <title>Register</title>
    <link href="{% static '/css/style.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300&display=swap" rel="stylesheet">

{% endblock head %}

{% block content %}
    <div class="container">
        <div class="header">
            <h1>Register Data</h1>
        </div>
        {% if messages %}
            <ul>
            {% for msg in messages %}
                <li id="error_text" {% if msg.tags %} class="{{msg.tags}}" {% endif %}>
                    {{msg}}
                </li>
            {% endfor %}
            </ul>
            <p id="error"></p>
        {% endif %}
        <div class="main">
            <form method="POST" action="" class="form" id="signupForm">
                {% csrf_token %}
                <div>
                    <label class="name">Name</label>
                    <input type="text" name="name" placeholder="Name" id="id_name">
                </div>
                <br>

                <div>
                    <label class="name">Email</label>
                    <input type="text" name="email" placeholder="Email" id="id_email">
                </div>
                <br>

                <div>
                    <label class="name">Contact</label>
                    <input type="number" name="contact" placeholder="Mobile Number" id="id_contact">
                </div>
                <br>

                <div>
                    <label class="name">Password</label>
                    <input type="password" name="password" placeholder="Password" id="id_password">
                </div>
                <br>
                <div>
                    <label class="name">Confirm Password</label>
                    <input type="password" name="re_password" placeholder="Password" id="id_re_password">
                </div>
                <br>

                <div>
                    <button type="submit" class="btn">Register</button>
                </div>
            </form>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.js"
            integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
            crossorigin="anonymous"></script>

    <script>
        $(document).on('submit', '#signupForm', function(e){
            e.preventDefault();
            var name = $(#id_name).val()
            var email = $(#id_email).val()
            var contact = $(#id_contact).val()
            var password = $(#id_password).val()
            var re_password = $(#id_re_password).val()

            $.ajax({
                type: 'POST',
                url: '/reg/',
                data = {
                    name: name,
                    email: email,
                    contact: contact,
                    password: password,
                    re_password: re_password,
                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
                },
                success:function(response){
                    console.log(response)
                    var error = $(response).find('#error_text')
                    console.log(error);
                    var error_class = $(error).attr('class')
                    console.log(error_class);
                    console.log(error.text())
                    $('#error').addClass(error_class)
                    $('#error').text(error.text())
                }
            })
        })
    </script>

{% endblock content %}

connective/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>User Login Data</title>
    <link href="{% static '/css/loginstyle.css' %}" rel="stylesheet" type="text/css">
</head>
<body>
    <!-- header start here -->
    <header>
        <div class="header-block">
            <div class="logo">
                <h2>Logbook</h2>
            </div>
            <div class="link">
                <div>
                    Login Connectivity :
                    <a href="{% url 'reg' %}">Registration</a> &nbsp; &nbsp;
                    <a href="{% url 'home' %}">Home</a>
                    <a href="{% url 'show' %}">Show</a>
                </div>
            </div>
        </div>
    </header>
    <!-- header end here -->

    <!-- container start here -->
    <div class="container">
        <div class="header">
            <div>
                <h1>Login Data</h1>
            </div>
        </div>
        <div class="main">
            <form method="POST" class="form" action="">
                {% csrf_token %}

                <div>
                    <label class="name">Email:</label>
                    <div class="col-sm-4">
                        <input type="text" name="email" class="text-box" required>
                    </div>
                </div>

                <div>
                    <label class="name">Password:</label>
                    <div class="col-sm-4">
                        <input type="password" name="password" class="text-box" required>
                    </div>
                </div>
                <br>

                <div>
                    <button type="submit" class="btn">Login</button>
                </div>
                <br>
                <hr>
                <a href="/reset/{{ employee.id }}"><span class="glyphicon glyphicon-pencil" >forget password.?</span></a>


                {% if messages %}
                    {% for msg in messages %}
                        <b>{{msg}}</b>
                    {% endfor %}
                {% endif %}
            </form>
        </div>
    <!-- Animation div -->
        <div class="highway"></div>
        <div class="city"></div>
        <div class="car">
            <img src="{% static '/img/car.png'%}">
        </div>
        <div class="wheel">
            <img src="{% static '/img/wheel.png'%}" class="front-wheel">
            <img src="{% static '/img/wheel.png'%}" class="back-wheel">
        </div>

        <div class="car1">
            <img src="{% static '/img/car.png'%}">
        </div>
        <div class="wheel1">
            <img src="{% static '/img/wheel.png'%}" class="front-wheel">
            <img src="{% static '/img/wheel.png'%}" class="back-wheel">
        </div>
    </div>
    <!-- container end here -->
</body>
</html>

connective/templates/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Person Records</title>
     {% load static %}
    <link rel="stylesheet" href="{% static 'css/show.css' %}"/>
</head>
<body>
<div class="container">
    <table class="main">
        <thead class="thead-dark">
        <tr>
            <th>Name &nbsp; &nbsp;</th>
            <th>Email &nbsp; &nbsp;</th>
            <th>Contact &nbsp; &nbsp;</th>
            <th>Password &nbsp; &nbsp;</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
    {% for employee in employees %}
        <tr>
            <td>{{ employee.name }} &nbsp; &nbsp;</td> &nbsp; &nbsp;
            <td>{{ employee.email }} &nbsp; &nbsp;</td> &nbsp; &nbsp;
            <td>{{ employee.contact }} &nbsp; &nbsp;</td> &nbsp; &nbsp;
            <td>{{ employee.password }} &nbsp; &nbsp;</td> &nbsp; &nbsp;
            <td>
                <a href="/edit/{{ employee.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>
                <a href="/delete/{{ employee.id }}">Delete</a>
            </td>
        </tr>
    {% endfor %}
        </tbody>
    </table>
</div>
<br>
<br>
    <div class="sub-body">
        <center class="cover"><a href="reg" class="btn btn-primary">Add New Record</a></center>
        <center class="cover_1"><a href="login" class="btn btn-primary">Login</a></center>
    </div>
<br>
<hr/>
    {% if messages %}
        {% for msg in messages %}
            <b>{{msg}}</b>
        {% endfor %}
    {% endif %}
<hr/>
</body>
</html>

connective/templates/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html><!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Logbook</title>

    <!-- favicon start -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'img/favicon/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'img/favicon/safari-pinned-tab.svg' %}" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <!-- favicon end -->
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <hr/>

<!-- Start Login Profile Page -->
        {% if request.session.email %}
        <head>
            {% load static %}
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-icons/3.0.1/iconfont/material-icons.min.css">
            <link href="{% static '/css/logstyle.css'%}" rel="stylesheet" type="text/css">
            <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v9.0" nonce="cCnaQCqu"></script>
            <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v9.0" nonce="HAqYibD7"></script>
        </head>
        <body>

    <!-- header start from here -->
        <div class="header1">
            <div id="logo" class="header1">
                <h1>Logbook</h1>
            </div>
            <div id="searcharea" class="header1">
                <input type="text" placeholder="search here" id="searchbox">
            </div>
            <div id="profilearea" class="header1">
                <a href="{{request.session.email}}">
                    <img src="{% static '/img/profile.png' %}" id="profilepic">
                    <span>{{request.session.email}}</span>
                </a>
            </div>
            <div id="profilearea1" class="header1">
                <a href="">Profile</a>
            </div>

            <div id="profilearea2" class="header1">|</div>

            <div id="homearea" class="header1">
                <a href="{% url 'home' %}">Home</a>
            </div>

            <div id="friendarea" class="header1">
                <a href="">
                    <img src="{% static '/img/frd.png' %}" id="friendpic">
                </a>
            </div>

            <div id="chatarea" class="header1">
                <a href="">
                    <img src="{% static '/img/chat.png' %}" id="chatpic">
                </a>
            </div>

            <div id="bellarea" class="header1">
                <a href="">
                    <img src="{% static '/img/bell.png' %}" id="bellpic">
                </a>
            </div>

            <div id="setarea2" class="header1">|</div>

            <div id="setarea" class="header1">
                <a href="">
                    <img src="{% static '/img/settings.png' %}" id="setpic">
                </a>
            </div>

            <div id="logoutarea" class="header1">
                <a href="{% url 'logout' %}">
                    <img src="{% static '/img/logout.png' %}" id="logpic">
                </a>
            </div>

            <div id="resetarea" class="header1">
                <a href="/change/{{ employee.id }}">
                    <img src="{% static '/img/reset.png' %}" id="resetpic">
                </a>
            </div>

        </div>    <!--- main email call here --->

    <!-- header end here -->

        </body>

<!-- End Login Profile Page -->

<!-- Start Home Page For link of Registration and Login -->

        {% else %}
        <head>
            {% load static %}
            <style>
                @import url('https://fonts.googleapis.com/css?family=Robot:300,400,500,700,900display=swap');
                * {
                    padding: 0px;
                    margin: 0px;
                    box-sizing: border-box;
                }

                body {
                    position: absolute;
                    width: 100%;
                    min-height: 100%;
                }

                header {
                    background: #415e9b;
                    height: 25%;
                    border-bottom: 1px solid #133783;
                }

                header .logo {
                    color: #fff;
                    font-size: 28px;
                    margin-left: 12%;
                    padding-top: 15px;
                    position: absolute;
                }

                header .link {
                    color: #fff;
                    font-size: 24px;
                    text-align: right;
                    padding-top: 40px;
                    padding-right: 40px;
                    word-spacing: 5px;
                }

                .link a {
                    text-decoration: none;
                    color: #000;
                }

                .main {
                    position: absolute;
                    overflow: hidden;
                    display: flex;
                    width: 100%;
                    min-height: 90vh;
                    background: #e80202;
                    justify-content: center;
                    align-items: center;
                }

                .container {
                    position: absolute;
                    align-items: center;
                    width: 100%;
                    height: 100%;
                    display: flex;
                    justify-content: center;
                }

                h1 {
                    color: #fff;
                    text-align: center;
                    font-size: 8vw;
                    line-height: 1em;
                    z-index: 1000;
                    font-weight: 900;
                }

                h1 span {
                    font-size: 0.3em;
                    letter-spacing: 0.2em;
                    font-weight: 400;
                    text-transform: uppercase;
                }

                .block {
                    position: absolute;
                    width: 50px;
                    height: 100px;
                    background: #e80202;
                    box-shadow: 10px 10px 50px rgba(0, 0, 0, 0.2)
                }
            </style>
        </head>

        <header>
            <div class="header-block">
                <div class="logo">
                    <h2>Logbook</h2>
                </div>
                <div class="link">
                    <div>
                        Login Connectivity :
                        <a href="{% url 'reg' %}">Registration</a> &nbsp; &nbsp;
                        <a href="{% url 'log' %}">Login</a> &nbsp;
                        <a href="{% url 'show' %}">Show</a>
                    </div>
                </div>
            </div>
        </header>
        <div class="main">
            <div class="container">
                <h1><span>Welcome to</span><br>LogBook</h1>
            </div>

            <script src="{% static '/js/anime.min.js' %}"></script>
            <script>
                const container = document.querySelector('.container')
                for (var i =0; i<=40; i++){
                    const blocks = document.createElement('div');
                    blocks.classList.add('block');
                    container.appendChild(blocks);
                }

                function animateBlocks(){
                    anime({
                        targets: '.block',
                        translateX: function(){
                            return anime.random(-700, 700);
                        },
                        translateY: function(){
                            return anime.random(-500, 500);
                        },
                        scale: function(){
                            return anime.random(1,5);
                        },

                        easing: 'linear',
                        duration: 1000,
                        delay: anime.stagger(10),
                        complete: animateBlocks,
                    })
                }

                animateBlocks()
            </script>
        </div>
        {% endif %}
    </form>
</body>
</html>